{
 "title": "personal-finances-ext",
 "time": { "from": "2022-12-30T23:00:00.000Z", "to": "2030-01-01T22:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "account",
    "label": "Bank account",
    "query": "SELECT DISTINCT iban FROM finances.history ORDER BY iban;"
   }
  ]
 },
 "panels": [
  {
   "title": "Category",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \n  TO_CHAR(date, 'YYYY-MM') AS month,\n    SUM(CASE WHEN category = 'NOMINA' THEN amount ELSE 0 END) AS NOMINA,\n    SUM(CASE WHEN category = 'VIVIENDA' THEN amount ELSE 0 END) AS VIVIENDA,\n    SUM(CASE WHEN category = 'INVERSION' THEN amount ELSE 0 END) AS INVERSION,\n    SUM(CASE WHEN category = 'AMAZON' THEN amount ELSE 0 END) AS AMAZON,\n    SUM(CASE WHEN category = 'AWS' THEN amount ELSE 0 END) AS AWS,\n    SUM(CASE WHEN category = 'BAZAR' THEN amount ELSE 0 END) AS BAZAR,\n    SUM(CASE WHEN category = 'CAJERO' THEN amount ELSE 0 END) AS CAJERO,\n    SUM(CASE WHEN category = 'TRANSPORTE' THEN amount ELSE 0 END) AS TRANSPORTE,\n    SUM(CASE WHEN category = 'OCIO_DIG' THEN amount ELSE 0 END) AS OCIO_DIG\n    \n  FROM finances.history\n  WHERE $__timeFilter(date)\n    AND iban = '$account'\n  GROUP BY month\n  ORDER BY month;"
    }
   ]
  },
  {
   "title": "Current",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  TO_CHAR(date, 'YYYY-MM') AS month,\n  SUM(\"end\") AS total\nFROM finances.balances\nWHERE risk >= 0\nGROUP BY month\nORDER BY month DESC\nLIMIT 1;"
    },
    {
     "rawSql": "SELECT\n  TO_CHAR(date, 'YYYY-MM') AS month,\n  SUM(\"end\") AS total\nFROM finances.balances\nWHERE risk = 0\nGROUP BY month\nORDER BY month DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Keeped",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  date,\n  total,\n  patrimony\nFROM finances.monthly_summary\nWHERE $__timeFilter(date)\n"
    }
   ]
  },
  {
   "title": "Patrimony",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  DATE_TRUNC('month', date) AS time,\n  iban,\n  SUM(\"end\") AS value\nFROM finances.balances\nWHERE $__timeFilter(date)\nGROUP BY time, iban\nORDER BY time, iban;"
    }
   ]
  }
 ]
}