apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: grafana-locations
  description: grafana entities
spec:
  targets:
    - ./backstage/api.yaml
    - ./backstage/template-dashboards.yaml
