name: Build and Deploy Grafana

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  # tags:
  #   - "*"
  # pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      
      - name: Inject Grafana password into env file
        run: |
          echo "DS_POSTGRES_PASSWORD=${{ secrets.DS_POSTGRES_PASSWORD }}" >> env.grafana
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install plugin dependencies
        working-directory: mapdevs-fileuploader-app
        run: npm install
      
      - name: Build plugin
        working-directory: mapdevs-fileuploader-app
        run: npm run build

      - name: Build backend Go plugin
        working-directory: mapdevs-fileuploader-app/src/backend
        run: |
          go mod tidy
          GOOS=linux GOARCH=amd64 go build -o ../../dist/_linux_amd64 main.go
          
      - name: Build Docker image
        run: |
          docker build -t grafana-integration:latest .

      - name: Tag Docker image
        run: |
          docker tag grafana-integration:latest ghcr.io/marioapgs/grafana-integration:latest

      - name: Docker login to GHCR
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: |
          docker push ghcr.io/marioapgs/grafana-integration:latest

      - name: Trigger deployment on Render
        run: |
          curl -X GET "${{ secrets.RENDER_TRIGGER_URL }}"

